name: Build macOS binaries of Ungoogled Chromium
on:
  workflow_dispatch:
  push:

jobs:
  get-source:
    name: Get Chromium and dependencies source
    runs-on: macos-latest
    steps:
      - name: Save source
        run: |
          echo "source" > src.txt
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: src.txt

  build:
    needs: get-source
    name: Build macOS binaries of Ungoogled Chromium
    strategy:
      matrix:
        arch: [x86_64, arm64]
      fail-fast: true
      max-parallel: 2
    uses: ./.github/workflows/building.yml
    with:
      arch: ${{ matrix.arch }}

  release:
    needs: build
    name: Release macOS binaries of Ungoogled Chromium
    runs-on: macos-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Download x86_64 built
        uses: actions/download-artifact@v4
        with:
            name: built_x86_64
      - name: Download arm64 built
        uses: actions/download-artifact@v4
        with:
            name: built_arm64
      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}_release
          name: ${{ github.ref }} release
          draft: false
          prerelease: false
          files: built_*.txt
