name: Building macOS binaries of Ungoogled Chromium

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string

jobs:
  build_job_01:
    name: Start Building Ungoogled-Chromium for macOS
    runs-on: macos-13
    outputs:
      status: ${{ steps.build.outputs.status }}
    steps:
      - name: If release?
        run: echo "release = ${{ inputs.release }}"
      - name: Download source
        uses: actions/download-artifact@v3
        with:
            name: source
      - name: Display structure of downloaded files
        run: ls -R
      - name: Show source
        run: cat src.txt
      - name: Build
        id: build
        run: |
          cat src.txt >> built_${{ inputs.arch }}.txt
          echo "\narch = ${{ inputs.arch }}" >> built_${{ inputs.arch }}.txt
          echo "\nbuilding 01" >> built_${{ inputs.arch }}.txt
      - name: Upload built
        uses: actions/upload-artifact@v3
        with:
          name: built_${{ inputs.arch }}
          path: built_${{ inputs.arch }}.txt

  build_job_02:
    name: Continue Building Ungoogled-Chromium for macOS
    runs-on: macos-13
    needs: build_job_01
    steps:
      - name: Download built
        uses: actions/download-artifact@v3
        with:
            name: built_${{ inputs.arch }}
      - name: Continue build
        run: |
          echo "\nbuilding 02" >> built_${{ inputs.arch }}.txt
      - name: Upload built
        uses: actions/upload-artifact@v3
        with:
          name: built_${{ inputs.arch }}
          path: built_${{ inputs.arch }}.txt