name: Build macOS binaries of Ungoogled Chromium
on:
  workflow_dispatch:
  push:

jobs:
  get-source:
    name: Get Chromium and dependencies source
    runs-on: macos-latest
    steps:
      - name: Save source
        run: |
          echo "source" > src.txt
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: src.txt

  build:
    needs: get-source
    name: Build macOS binaries of Ungoogled Chromium
    strategy:
      matrix:
        arch: [x86_64, arm64]
      fail-fast: true
      max-parallel: 2
    uses: ./.github/workflows/building.yml
    with:
      arch: ${{ matrix.arch }}
      release: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
