name: Building macOS binaries of Ungoogled Chromium

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      release:
        required: true
        type: boolean

jobs:
  build_job_01:
    name: Start Building Ungoogled-Chromium for macOS
    runs-on: macos-13
    outputs:
      status: ${{ steps.build.outputs.status }}
    steps:
      - name: If release?
        run: echo "release = ${{ inputs.release }}"
      - name: Download source
        uses: actions/download-artifact@v4
        with:
            name: source
      - name: Display structure of downloaded files
        run: ls -R
      - name: Show source
        run: cat src.txt
      - name: Build
        id: build
        run: |
          cat src.txt >> built_${{ inputs.arch }}.txt
          echo "\narch = ${{ inputs.arch }}" >> built_${{ inputs.arch }}.txt
          echo "\nbuilding 01" >> built_${{ inputs.arch }}.txt
      - name: Create Release
        if: ${{ inputs.release && steps.build.outputs.status == 'finished' && github.event_name != 'pull_request' }}
        uses: softprops/action-gh-release@v1
        with:
          files: built_${{ inputs.arch }}.txt
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.ref }} release
          draft: false
          prerelease: false
